import { z } from "zod";
import type {
  GoodsReceiveNote,
  GrnDetailPayload,
  ExtraCostDetailPayload,
} from "@/types/goods-receive-note";
import { textToObject } from "@/lib/form-helpers";

// --- Detail item schema ---

export const grnDetailSchema = z.object({
  id: z.string().optional(),
  product_id: z
    .string()
    .nullable()
    .refine((v) => !!v, "Product is required"),
  purchase_order_detail_id: z.string().nullable(),
  product_name: z.string(),
  requested_qty: z.coerce.number().min(0),
  approved_qty: z.coerce.number().min(0),
  price: z.coerce.number().min(0),
  total_price: z.coerce.number(),
  price_without_vat: z.coerce.number(),
  price_with_vat: z.coerce.number(),
  base_price: z.coerce.number(),
  base_total_price: z.coerce.number(),
  extra_cost: z.coerce.number(),
  total_cost: z.coerce.number(),
  location_id: z.string().nullable(),
  location_name: z.string(),
  requested_unit_id: z.string().nullable(),
  requested_unit_name: z.string(),
  approved_unit_id: z.string().nullable(),
  approved_unit_name: z.string(),
  requested_base_qty: z.coerce.number(),
  requested_base_unit_id: z.string().nullable(),
  requested_base_unit_name: z.string(),
  approved_base_qty: z.coerce.number(),
  approved_base_unit_id: z.string().nullable(),
  approved_base_unit_name: z.string(),
  foc_qty: z.coerce.number(),
  foc_unit_id: z.string().nullable(),
  foc_unit_name: z.string(),
  foc_base_qty: z.coerce.number(),
  foc_base_unit_id: z.string().nullable(),
  foc_base_unit_name: z.string(),
  foc_unit_conversion_rate: z.coerce.number(),
  foc_base_unit_conversion_rate: z.coerce.number(),
  inventory_unit_id: z.string().nullable(),
  inventory_unit_name: z.string(),
  inventory_unit_qty: z.coerce.number(),
  inventory_unit_conversion_rate: z.coerce.number(),
  requested_unit_conversion_rate: z.coerce.number(),
  approved_unit_conversion_rate: z.coerce.number(),
  unit_id: z.string().nullable(),
  unit_name: z.string(),
  order_qty: z.coerce.number(),
  order_unit_id: z.string().nullable(),
  order_unit_name: z.string(),
  order_unit_conversion_rate: z.coerce.number(),
  order_base_qty: z.coerce.number(),
  order_base_unit_id: z.string().nullable(),
  order_base_unit_name: z.string(),
  received_qty: z.coerce.number().min(0),
  received_unit_id: z.string().nullable(),
  received_unit_name: z.string(),
  received_unit_conversion_rate: z.coerce.number(),
  received_base_unit_conversion_rate: z.coerce.number(),
  received_base_qty: z.coerce.number(),
  received_base_unit_id: z.string().nullable(),
  received_base_unit_name: z.string(),
  base_qty: z.coerce.number(),
  return_qty: z.coerce.number(),
  return_unit_id: z.string().nullable(),
  return_unit_name: z.string(),
  return_conversion_rate: z.coerce.number(),
  return_base_qty: z.coerce.number(),
  tax_profile_id: z.string().nullable(),
  tax_profile_name: z.string(),
  tax_rate: z.coerce.number(),
  tax_amount: z.coerce.number(),
  is_tax_adjustment: z.boolean(),
  base_tax_amount: z.coerce.number(),
  total_amount: z.coerce.number(),
  delivery_date: z.string().nullable(),
  delivery_date_id: z.string().nullable(),
  delivery_point_id: z.string().nullable(),
  delivery_point_name: z.string(),
});

// --- Extra cost detail schema ---

export const extraCostDetailSchema = z.object({
  id: z.string().optional(),
  extra_cost_type_id: z.string().min(1, "Type is required"),
  note: z.string(),
  info: z.string(),
  dimension: z.string(),
  amount: z.coerce.number().min(0),
  tax_profile_id: z.string().nullable(),
  tax_profile_name: z.string(),
  tax_rate: z.coerce.number(),
  tax_amount: z.coerce.number(),
  is_tax_adjustment: z.boolean(),
  base_tax_amount: z.coerce.number(),
  total_amount: z.coerce.number(),
  tax_type: z.string(),
});

// --- Main GRN schema ---

export const grnSchema = z.object({
  grn_date: z.string().min(1, "GRN date is required"),
  expired_date: z.string().nullable(),
  invoice_no: z.string(),
  invoice_date: z.string().nullable(),
  description: z.string(),
  note: z.string(),
  doc_status: z.string().min(1, "Status is required"),
  doc_type: z.string().min(1, "Type is required"),
  is_consignment: z.boolean(),
  is_cash: z.boolean(),
  signature_image_url: z.string(),
  received_by_id: z.string().nullable(),
  received_by_name: z.string(),
  received_at: z.string().nullable(),
  credit_term_id: z.string().nullable(),
  credit_term_name: z.string(),
  credit_term_days: z.coerce.number().nullable(),
  payment_due_date: z.string().nullable(),
  is_active: z.boolean(),
  vendor_id: z
    .string()
    .nullable()
    .refine((v) => !!v, "Vendor is required"),
  vendor_name: z.string(),
  approved_unit_conversion_factor: z.coerce.number().nullable(),
  requested_unit_conversion_factor: z.coerce.number().nullable(),
  currency_id: z.string().nullable(),
  currency_name: z.string(),
  exchange_rate: z.coerce.number().nullable(),
  exchange_rate_date: z.string().nullable(),
  discount_rate: z.coerce.number().nullable(),
  discount_amount: z.coerce.number().nullable(),
  is_discount_adjustment: z.boolean(),
  base_discount_amount: z.coerce.number().nullable(),
  info: z.string(),
  dimension: z.string(),
  // Extra cost header
  extra_cost_name: z.string(),
  extra_cost_note: z.string(),
  allocate_extracost_type: z.string(),
  // Arrays
  items: z.array(grnDetailSchema),
  extra_cost_details: z.array(extraCostDetailSchema),
});

export type GrnFormValues = z.infer<typeof grnSchema>;

// --- Default detail item ---

export const EMPTY_DETAIL: GrnFormValues["items"][number] = {
  product_id: null,
  purchase_order_detail_id: null,
  product_name: "",
  requested_qty: 0,
  approved_qty: 0,
  price: 0,
  total_price: 0,
  price_without_vat: 0,
  price_with_vat: 0,
  base_price: 0,
  base_total_price: 0,
  extra_cost: 0,
  total_cost: 0,
  location_id: null,
  location_name: "",
  requested_unit_id: null,
  requested_unit_name: "",
  approved_unit_id: null,
  approved_unit_name: "",
  requested_base_qty: 0,
  requested_base_unit_id: null,
  requested_base_unit_name: "",
  approved_base_qty: 0,
  approved_base_unit_id: null,
  approved_base_unit_name: "",
  foc_qty: 0,
  foc_unit_id: null,
  foc_unit_name: "",
  foc_base_qty: 0,
  foc_base_unit_id: null,
  foc_base_unit_name: "",
  foc_unit_conversion_rate: 0,
  foc_base_unit_conversion_rate: 0,
  inventory_unit_id: null,
  inventory_unit_name: "",
  inventory_unit_qty: 0,
  inventory_unit_conversion_rate: 0,
  requested_unit_conversion_rate: 0,
  approved_unit_conversion_rate: 0,
  unit_id: null,
  unit_name: "",
  order_qty: 0,
  order_unit_id: null,
  order_unit_name: "",
  order_unit_conversion_rate: 0,
  order_base_qty: 0,
  order_base_unit_id: null,
  order_base_unit_name: "",
  received_qty: 0,
  received_unit_id: null,
  received_unit_name: "",
  received_unit_conversion_rate: 0,
  received_base_unit_conversion_rate: 0,
  received_base_qty: 0,
  received_base_unit_id: null,
  received_base_unit_name: "",
  base_qty: 0,
  return_qty: 0,
  return_unit_id: null,
  return_unit_name: "",
  return_conversion_rate: 0,
  return_base_qty: 0,
  tax_profile_id: null,
  tax_profile_name: "",
  tax_rate: 0,
  tax_amount: 0,
  is_tax_adjustment: false,
  base_tax_amount: 0,
  total_amount: 0,
  delivery_date: null,
  delivery_date_id: null,
  delivery_point_id: null,
  delivery_point_name: "",
};

// --- Default extra cost detail ---

export const EMPTY_EXTRA_COST: GrnFormValues["extra_cost_details"][number] = {
  extra_cost_type_id: "",
  note: "",
  info: "",
  dimension: "",
  amount: 0,
  tax_profile_id: null,
  tax_profile_name: "",
  tax_rate: 0,
  tax_amount: 0,
  is_tax_adjustment: false,
  base_tax_amount: 0,
  total_amount: 0,
  tax_type: "none",
};

// --- Helpers ---

const objectToText = (
  value: Record<string, unknown> | null | undefined,
): string => {
  if (!value || Object.keys(value).length === 0) return "";
  return JSON.stringify(value, null, 2);
};

export function getDefaultValues(grn?: GoodsReceiveNote): GrnFormValues {
  if (!grn) {
    return {
      grn_date: new Date().toISOString(),
      expired_date: null,
      invoice_no: "",
      invoice_date: null,
      description: "",
      note: "",
      doc_status: "draft",
      doc_type: "purchase_order",
      is_consignment: false,
      is_cash: false,
      signature_image_url: "",
      received_by_id: null,
      received_by_name: "",
      received_at: null,
      credit_term_id: null,
      credit_term_name: "",
      credit_term_days: null,
      payment_due_date: null,
      is_active: true,
      vendor_id: null,
      vendor_name: "",
      approved_unit_conversion_factor: null,
      requested_unit_conversion_factor: null,
      currency_id: null,
      currency_name: "",
      exchange_rate: null,
      exchange_rate_date: null,
      discount_rate: null,
      discount_amount: null,
      is_discount_adjustment: false,
      base_discount_amount: null,
      info: "",
      dimension: "",
      extra_cost_name: "",
      extra_cost_note: "",
      allocate_extracost_type: "by_qty",
      items: [],
      extra_cost_details: [],
    };
  }

  return {
    grn_date: grn.grn_date ?? "",
    expired_date: grn.expired_date,
    invoice_no: grn.invoice_no ?? "",
    invoice_date: grn.invoice_date,
    description: grn.description ?? "",
    note: grn.note ?? "",
    doc_status: grn.doc_status,
    doc_type: grn.doc_type,
    is_consignment: grn.is_consignment,
    is_cash: grn.is_cash,
    signature_image_url: grn.signature_image_url ?? "",
    received_by_id: grn.received_by_id,
    received_by_name: grn.received_by_name ?? "",
    received_at: grn.received_at,
    credit_term_id: grn.credit_term_id,
    credit_term_name: grn.credit_term_name ?? "",
    credit_term_days: grn.credit_term_days,
    payment_due_date: grn.payment_due_date,
    is_active: grn.is_active,
    vendor_id: grn.vendor_id,
    vendor_name: grn.vendor_name ?? "",
    approved_unit_conversion_factor: grn.approved_unit_conversion_factor,
    requested_unit_conversion_factor: grn.requested_unit_conversion_factor,
    currency_id: grn.currency_id,
    currency_name: grn.currency_name ?? "",
    exchange_rate: grn.exchange_rate,
    exchange_rate_date: grn.exchange_rate_date,
    discount_rate: grn.discount_rate,
    discount_amount: grn.discount_amount,
    is_discount_adjustment: grn.is_discount_adjustment,
    base_discount_amount: grn.base_discount_amount,
    info: objectToText(grn.info),
    dimension: objectToText(grn.dimension),
    extra_cost_name: grn.extra_cost?.name ?? "",
    extra_cost_note: grn.extra_cost?.note ?? "",
    allocate_extracost_type:
      grn.extra_cost?.allocate_extracost_type ?? "by_qty",
    items:
      grn.good_received_note_detail?.map((d) => ({
        id: d.id,
        product_id: d.product_id,
        purchase_order_detail_id: d.purchase_order_detail_id,
        product_name: d.product_name ?? "",
        requested_qty: d.requested_qty,
        approved_qty: d.approved_qty,
        price: d.price,
        total_price: d.total_price,
        price_without_vat: d.price_without_vat,
        price_with_vat: d.price_with_vat,
        base_price: d.base_price,
        base_total_price: d.base_total_price,
        extra_cost: d.extra_cost,
        total_cost: d.total_cost,
        location_id: d.location_id,
        location_name: d.location_name ?? "",
        requested_unit_id: d.requested_unit_id,
        requested_unit_name: d.requested_unit_name ?? "",
        approved_unit_id: d.approved_unit_id,
        approved_unit_name: d.approved_unit_name ?? "",
        requested_base_qty: d.requested_base_qty,
        requested_base_unit_id: d.requested_base_unit_id,
        requested_base_unit_name: d.requested_base_unit_name ?? "",
        approved_base_qty: d.approved_base_qty,
        approved_base_unit_id: d.approved_base_unit_id,
        approved_base_unit_name: d.approved_base_unit_name ?? "",
        foc_qty: d.foc_qty,
        foc_unit_id: d.foc_unit_id,
        foc_unit_name: d.foc_unit_name ?? "",
        foc_base_qty: d.foc_base_qty,
        foc_base_unit_id: d.foc_base_unit_id,
        foc_base_unit_name: d.foc_base_unit_name ?? "",
        foc_unit_conversion_rate: d.foc_unit_conversion_rate,
        foc_base_unit_conversion_rate: d.foc_base_unit_conversion_rate,
        inventory_unit_id: d.inventory_unit_id,
        inventory_unit_name: d.inventory_unit_name ?? "",
        inventory_unit_qty: d.inventory_unit_qty,
        inventory_unit_conversion_rate: d.inventory_unit_conversion_rate,
        requested_unit_conversion_rate: d.requested_unit_conversion_rate,
        approved_unit_conversion_rate: d.approved_unit_conversion_rate,
        unit_id: d.unit_id,
        unit_name: d.unit_name ?? "",
        order_qty: d.order_qty,
        order_unit_id: d.order_unit_id,
        order_unit_name: d.order_unit_name ?? "",
        order_unit_conversion_rate: d.order_unit_conversion_rate,
        order_base_qty: d.order_base_qty,
        order_base_unit_id: d.order_base_unit_id,
        order_base_unit_name: d.order_base_unit_name ?? "",
        received_qty: d.received_qty,
        received_unit_id: d.received_unit_id,
        received_unit_name: d.received_unit_name ?? "",
        received_unit_conversion_rate: d.received_unit_conversion_rate,
        received_base_unit_conversion_rate:
          d.received_base_unit_conversion_rate,
        received_base_qty: d.received_base_qty,
        received_base_unit_id: d.received_base_unit_id,
        received_base_unit_name: d.received_base_unit_name ?? "",
        base_qty: d.base_qty,
        return_qty: d.return_qty,
        return_unit_id: d.return_unit_id,
        return_unit_name: d.return_unit_name ?? "",
        return_conversion_rate: d.return_conversion_rate,
        return_base_qty: d.return_base_qty,
        tax_profile_id: d.tax_profile_id,
        tax_profile_name: d.tax_profile_name ?? "",
        tax_rate: d.tax_rate,
        tax_amount: d.tax_amount,
        is_tax_adjustment: d.is_tax_adjustment,
        base_tax_amount: d.base_tax_amount,
        total_amount: d.total_amount,
        delivery_date: d.delivery_date,
        delivery_date_id: d.delivery_date_id,
        delivery_point_id: d.delivery_point_id,
        delivery_point_name: d.delivery_point_name ?? "",
      })) ?? [],
    extra_cost_details:
      grn.extra_cost?.extra_cost_detail?.map((d) => ({
        id: d.id,
        extra_cost_type_id: d.extra_cost_type_id,
        note: d.note ?? "",
        info: objectToText(d.info),
        dimension: objectToText(d.dimension),
        amount: d.amount,
        tax_profile_id: d.tax_profile_id,
        tax_profile_name: d.tax_profile_name ?? "",
        tax_rate: d.tax_rate,
        tax_amount: d.tax_amount,
        is_tax_adjustment: d.is_tax_adjustment,
        base_tax_amount: d.base_tax_amount,
        total_amount: d.total_amount,
        tax_type: d.tax_type ?? "none",
      })) ?? [],
  };
}

// --- Map form item → API payload ---

export function mapDetailToPayload(
  item: GrnFormValues["items"][number],
): GrnDetailPayload {
  return {
    product_id: item.product_id || "",
    purchase_order_detail_id: item.purchase_order_detail_id,
    product_name: item.product_name,
    requested_qty: item.requested_qty,
    approved_qty: item.approved_qty,
    price: item.price,
    total_price: item.total_price,
    price_without_vat: item.price_without_vat,
    price_with_vat: item.price_with_vat,
    base_price: item.base_price,
    base_total_price: item.base_total_price,
    extra_cost: item.extra_cost,
    total_cost: item.total_cost,
    location_id: item.location_id,
    location_name: item.location_name,
    requested_unit_id: item.requested_unit_id,
    requested_unit_name: item.requested_unit_name,
    approved_unit_id: item.approved_unit_id,
    approved_unit_name: item.approved_unit_name,
    requested_base_qty: item.requested_base_qty,
    requested_base_unit_id: item.requested_base_unit_id,
    requested_base_unit_name: item.requested_base_unit_name,
    approved_base_qty: item.approved_base_qty,
    approved_base_unit_id: item.approved_base_unit_id,
    approved_base_unit_name: item.approved_base_unit_name,
    foc_qty: item.foc_qty,
    foc_unit_id: item.foc_unit_id,
    foc_unit_name: item.foc_unit_name,
    foc_base_qty: item.foc_base_qty,
    foc_base_unit_id: item.foc_base_unit_id,
    foc_base_unit_name: item.foc_base_unit_name,
    foc_unit_conversion_rate: item.foc_unit_conversion_rate,
    foc_base_unit_conversion_rate: item.foc_base_unit_conversion_rate,
    inventory_unit_id: item.inventory_unit_id,
    inventory_unit_name: item.inventory_unit_name,
    inventory_unit_qty: item.inventory_unit_qty,
    inventory_unit_conversion_rate: item.inventory_unit_conversion_rate,
    requested_unit_conversion_rate: item.requested_unit_conversion_rate,
    approved_unit_conversion_rate: item.approved_unit_conversion_rate,
    unit_id: item.unit_id,
    unit_name: item.unit_name,
    order_qty: item.order_qty,
    order_unit_id: item.order_unit_id,
    order_unit_name: item.order_unit_name,
    order_unit_conversion_rate: item.order_unit_conversion_rate,
    order_base_qty: item.order_base_qty,
    order_base_unit_id: item.order_base_unit_id,
    order_base_unit_name: item.order_base_unit_name,
    received_qty: item.received_qty,
    received_unit_id: item.received_unit_id,
    received_unit_name: item.received_unit_name,
    received_unit_conversion_rate: item.received_unit_conversion_rate,
    received_base_unit_conversion_rate: item.received_base_unit_conversion_rate,
    received_base_qty: item.received_base_qty,
    received_base_unit_id: item.received_base_unit_id,
    received_base_unit_name: item.received_base_unit_name,
    base_qty: item.base_qty,
    return_qty: item.return_qty,
    return_unit_id: item.return_unit_id,
    return_unit_name: item.return_unit_name,
    return_conversion_rate: item.return_conversion_rate,
    return_base_qty: item.return_base_qty,
    tax_profile_id: item.tax_profile_id,
    tax_profile_name: item.tax_profile_name,
    tax_rate: item.tax_rate,
    tax_amount: item.tax_amount,
    is_tax_adjustment: item.is_tax_adjustment,
    base_tax_amount: item.base_tax_amount,
    total_amount: item.total_amount,
    delivery_date: item.delivery_date,
    delivery_date_id: item.delivery_date_id,
    delivery_point_id: item.delivery_point_id,
    delivery_point_name: item.delivery_point_name,
  };
}

export function mapExtraCostToPayload(
  item: GrnFormValues["extra_cost_details"][number],
): ExtraCostDetailPayload {
  return {
    extra_cost_type_id: item.extra_cost_type_id,
    note: item.note,
    info: textToObject(item.info),
    dimension: textToObject(item.dimension),
    amount: item.amount,
    tax_profile_id: item.tax_profile_id,
    tax_profile_name: item.tax_profile_name,
    tax_rate: item.tax_rate,
    tax_amount: item.tax_amount,
    is_tax_adjustment: item.is_tax_adjustment,
    base_tax_amount: item.base_tax_amount,
    total_amount: item.total_amount,
    tax_type: item.tax_type,
  };
}
