export const PR_ITEM = {
  product_id: "",
  product_name: "",
  description: "",
  unit_price: 0,
  vendor_id: "",
  vendor_name: "",
  current_stage_status: "draft",
  location_id: "",
  requested_qty: 1,
  requested_unit_id: "",
  requested_unit_name: "",
  foc_qty: 0,
  foc_unit_id: "",
  foc_unit_name: "",
  approved_qty: 0,
  approved_unit_id: "",
  approved_unit_name: "",
  currency_id: "",
  delivery_point_id: "",
  delivery_date: "",
  pricelist_detail_id: null,
  pricelist_no: null,
} as const;
