export const QUERY_KEYS = {
  PROFILE: "profile",
  BUSINESS_TYPES: "business-types",
  EXTRA_COSTS: "extra-costs",
  UNITS: "units",
  DELIVERY_POINTS: "delivery-points",
  DEPARTMENTS: "departments",
  LOCATIONS: "locations",
  ADJUSTMENT_TYPES: "adjustment-types",
  TAX_PROFILES: "tax-profiles",
  CURRENCIES: "currencies",
  PRODUCTS: "products",
  VENDORS: "vendors",
  PRICE_LISTS: "price-lists",
  PRICE_LIST_TEMPLATES: "price-list-templates",
  REQUEST_PRICE_LISTS: "request-price-lists",
  PERMISSIONS: "permissions",
  APPLICATION_ROLES: "application-roles",
  STORE_REQUISITIONS: "store-requisitions",
  WORKFLOWS: "workflows",
  INVENTORY_ADJUSTMENTS: "inventory-adjustments",
  PURCHASE_REQUESTS: "purchase-requests",
  MY_PENDING_PURCHASE_REQUESTS: "my-pending-purchase-requests",
  PURCHASE_REQUEST_WORKFLOW_STAGES: "purchase-request-workflow-stages",
  PURCHASE_REQUEST_TEMPLATES: "purchase-request-templates",
  PURCHASE_REQUEST_COMMENTS: "purchase-request-comments",
} as const;

export type QueryKey = (typeof QUERY_KEYS)[keyof typeof QUERY_KEYS];
