export const QUERY_KEYS = {
  ADJUSTMENT_TYPES: "adjustment-types",
  APPLICATION_ROLES: "application-roles",
  BUSINESS_TYPES: "business-types",
  CREDIT_NOTES: "credit-notes",
  CURRENCIES: "currencies",
  DELIVERY_POINTS: "delivery-points",
  DEPARTMENTS: "departments",
  DOCUMENTS: "documents",
  EXCHANGE_RATES: "exchange-rates",
  EXTRA_COSTS: "extra-costs",
  GOODS_RECEIVE_NOTES: "goods-receive-notes",
  INVENTORY_ADJUSTMENTS: "inventory-adjustments",
  LOCATIONS: "locations",
  MY_PENDING_PURCHASE_REQUESTS: "my-pending-purchase-requests",
  PERIOD_ENDS: "period-ends",
  PERMISSIONS: "permissions",
  PHYSICAL_COUNTS: "physical-counts",
  PRICE_LISTS: "price-lists",
  PRICE_LIST_TEMPLATES: "price-list-templates",
  PRODUCTS: "products",
  PRODUCT_CATEGORIES: "product-categories",
  PRODUCT_ITEM_GROUPS: "product-item-groups",
  PRODUCT_SUB_CATEGORIES: "product-sub-categories",
  PROFILE: "profile",
  PURCHASE_ORDERS: "purchase-orders",
  PURCHASE_REQUESTS: "purchase-requests",
  PURCHASE_REQUEST_COMMENTS: "purchase-request-comments",
  PURCHASE_REQUEST_TEMPLATES: "purchase-request-templates",
  PURCHASE_REQUEST_WORKFLOW_STAGES: "purchase-request-workflow-stages",
  REQUEST_PRICE_LISTS: "request-price-lists",
  SPOT_CHECKS: "spot-checks",
  STORE_REQUISITIONS: "store-requisitions",
  TAX_PROFILES: "tax-profiles",
  UNITS: "units",
  USERS: "users",
  VENDORS: "vendors",
  WORKFLOWS: "workflows",
} as const;

export type QueryKey = (typeof QUERY_KEYS)[keyof typeof QUERY_KEYS];
